env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-console: 0
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  react/jsx-indent: [2, 2, {"checkAttributes": true, "indentLogicalExpressions": true}]
  react/jsx-first-prop-new-line: [2, 'multiline']
  react/jsx-max-props-per-line: [2, { "when": "multiline" }]
  react/jsx-wrap-multilines: [2, { "prop": "parens", "logical": "parens" }]
  react/jsx-closing-tag-location: [2]
  react/jsx-one-expression-per-line: [2, { "allow": "single-child" }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-tag-spacing: [2, { "beforeClosing": "proportional-always" }]
  jsx-quotes: [2, 'prefer-double']
  react/jsx-indent-props: [2, 2]
  react-hooks/exhaustive-deps: 'warn'
  react/jsx-boolean-value: [2, 'never']
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-param-reassign: [2, { "props": false }]