env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-console: 0
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-param-reassign: [2, { "props": false }]